//1º V1 DO NUMBR: npx playwright codegen https://dev.bankr.com.br/login
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dev.bankr.com.br/login');
  await page.getByRole('textbox', { name: 'e-mail*' }).click();
  await page.getByRole('textbox', { name: 'e-mail*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e-mail*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e-mail*' }).fill('');
  await page.getByRole('textbox', { name: 'e-mail*' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'e-mail*' }).fill('samuel@numbr.com.br');
  await page.getByRole('textbox', { name: 'e-mail*' }).press('Tab');
  await page.getByRole('textbox', { name: 'Senha*' }).fill('wink12345');
  await page.getByRole('button', { name: 'Entrar' }).click();
  await page.getByRole('link', { name: 'Contratos' }).click();
  await page.getByRole('button', { name: 'Novo Contrato' }).click();
  await page.getByRole('textbox', { name: 'Buscar cliente*' }).click();
  await page.getByRole('textbox', { name: 'Buscar cliente*' }).fill('samu');
  await page.getByRole('button', { name: '51.017.581 SAMUEL HENRIQUE' }).click();
  await page.getByRole('textbox', { name: 'Valor*' }).click();
  await page.getByRole('textbox', { name: 'Valor*' }).fill('17');
  await page.getByRole('checkbox', { name: 'Habilitar juros e multa' }).check();
  await page.getByRole('checkbox', { name: 'Habilitar juros e multa' }).press('2');
  await page.getByRole('textbox', { name: 'Juros ao mês' }).click();
  await page.getByRole('textbox', { name: 'Multa por atraso' }).click();
  await page.getByRole('textbox', { name: 'Multa por atraso' }).click();
  await page.getByRole('textbox', { name: 'Multa por atraso' }).fill('2');
  await page.getByRole('textbox', { name: 'Juros ao mês' }).click();
  await page.getByRole('textbox', { name: 'Juros ao mês' }).fill('2');
  await page.getByRole('radio', { name: 'Boleto / Pix' }).check();
  await page.getByRole('checkbox', { name: 'Gerar NFS-e automaticamente' }).check();
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).click();
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).fill('testes ');
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).fill('testes QA.');
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Descrição para NFS-e **' }).fill('teste QA.');
  await page.getByRole('spinbutton', { name: 'Dias antes do vencimento' }).click();
  await page.getByRole('spinbutton', { name: 'Dias antes do vencimento' }).fill('1');
  await page.getByRole('spinbutton', { name: 'Intervalo entre avisos (dias)' }).click();
  await page.getByRole('spinbutton', { name: 'Intervalo entre avisos (dias)' }).fill('1');
  await page.getByText('CancelarSalvar').click();
  await page.getByRole('textbox', { name: 'Descrição do contrato (' }).click();
  await page.getByRole('textbox', { name: 'Descrição do contrato (' }).fill('TESTE AUTOMATIZADO DE CRIAÇ');
 // await page.getByRole('textbox', { name: 'Descrição do contrato (' }).press('Dead');
  await page.getByRole('textbox', { name: 'Descrição do contrato (' }).fill('TESTE AUTOMATIZADO DE CRIAÇÃO DE CONTRATO.');
  await page.getByRole('button', { name: 'Salvar' }).click();
  await page.getByRole('link', { name: 'Contratos' }).click();
  await page.locator('th:nth-child(9) > .inline-flex.items-center.gap-1 > .relative').click();
  await page.getByRole('button', { name: 'Ativo' }).click();
  await page.getByText('Filtrar', { exact: true }).click();
});